write config files to /etc and remove systemd generator
As all written files and created directories are noted in
/var/lib/tliset/paths.txt, the script can warn about stalled config
files that are no longer created.

diff --git a/host-setup b/host-setup
--- a/host-setup
+++ b/host-setup
@@ -43,9 +43,6 @@ readonly dev_docker_network_prefix="192.168.96"
 readonly dev_vz_network_prefix="192.168.97"
 
 readonly gen_self_dir="/run/tliset"
-readonly gen_scripts="$gen_self_dir"
-readonly gen_config="$gen_self_dir"
-readonly gen_mount="$gen_self_dir/set"
 
 bergenrabbit_dns="www.bergenrabbit.net bergenrabbit.net"
 bergenrabbit_dns="${bergenrabbit_dns} www.bergenrabbit.no bergenrabbit.no"
@@ -171,24 +168,59 @@ fixup_transgui() {
     local line='MimeType=application/x-bittorrent;x-scheme-handler/magnet;'
     if ! grep -q "^$line\$" "$path" ; then
 	log "fixing $path"
-	local data="$(cat "$path" | grep -v '^MimeType=')"
-	local tmp="$(mktemp "$path.XXXXXXXXXX")"
-	tmp_files+=($tmp)
-	printf '%s\n%s\n' "$data" "$line" > "$tmp"
-	chmod 644 "$tmp"
-	mv "$tmp" "$path"
+	local data
+	data="$(grep -v '^MimeType=' ${path})"
+	printf '%s\n%s\n' "$data" "$line" > "${path}.tmp"
+	chmod 644 "${path}.tmp"
+	mv "${path}.tmp" "${path}"
     fi
+}
+
+begin_tliset() {
+    paths_file=/var/lib/tliset/paths.txt
+    readonly paths_file
+    ensure_dir /var/lib/tliset
+    exec 9>>"${paths_file}.new"
+}
+
+end_tliset() {
+    exec 9>&-
+    local sorted
+    sort "${paths_file}.new" > "${paths_file}.tmp"
+    mv "${paths_file}.tmp" "${paths_file}.new"
+
+    # Duplicates happens when tliset runs again after a failure
+    uniq "${paths_file}.new" > "${paths_file}.tmp"
+    mv "${paths_file}.tmp" "${paths_file}.new"
+
+    if test -f "${paths_file}"; then
+	comm -23 "${paths_file}" "${paths_file}.new" > "${paths_file}.unknown"
+	filter_existing_paths < "${paths_file}.unknown" > "${paths_file}.tmp"
+	mv "${paths_file}.tmp" "${paths_file}.unknown"
+	if test -s "${paths_file}.unknown"; then
+	    log "No longer generated files from the previous runs:" \
+		"${NL}$(cat "${paths_file}.unknown")"
+	fi
+	sort "${paths_file}.new" "${paths_file}.unknown" > "${paths_file}.tmp"
+	mv "${paths_file}.tmp" "${paths_file}.new"
+    fi
+
+    mv "${paths_file}.new" "${paths_file}"
+}
+
+filter_existing_paths() {
+    local line
+    while IFS= read -r line; do
+	if test -e "${line}" -o -h "${line}"; then
+	    printf '%s\n' "${line}"
+	fi
+    done
 }
 
 note_path() {
     local path
     path="$1"
     printf '%s\n' "${path}" 1>&9
-}
-
-setup_tliset() {
-    ensure_dir /var/lib/tliset
-    exec 9>/var/lib/tliset/paths_new.txt
 }
 
 setup_packages() {
@@ -243,7 +275,7 @@ setup_fedora_packages() {
 	    udftools inotify-tools fdupes fslint mtools
 
 	    # encryption and backup
-	    apg duplicity perl-Digest-Bcrypt python-gdata
+	    apg duplicity perl-Digest-Bcrypt
 
 	    # Recovery tools
 	    ddrescue foremost scalpel testdisk
@@ -284,12 +316,12 @@ setup_fedora_packages() {
 
 	list+=(
 	    # hardware management
-	    rfkill lm_sensors
+	    util-linux lm_sensors
 	)
 
 
 	list+=(
-	    gnome-tweak-tool
+	    gnome-tweaks
 	    gnome-terminal-nautilus
 	    gnome-shell-extension-alternate-tab
 	)
@@ -474,9 +506,7 @@ start_generator_write() {
     multi_user_wants=()
     sockets_wants=()
     basic_target_wants=()
-    gen_body=()
-    gen_mkdir_list=()
-    with_nspawn_configs=
+    systemd_unit_update=
 }
 
 print_wants_list() {
@@ -493,54 +523,13 @@ print_wants_list() {
 }
 
 finish_generator_write() {
-    if [[ ${with_nspawn_configs} ]]; then
-	p_dir nspawn:
-    fi
-    p_dir scripts:
     print_wants_list multi-user.target "${multi_user_wants[@]:+${multi_user_wants[@]}}"
     print_wants_list sockets.target "${socket_wants[@]:+${socket_wants[@]}}"
     print_wants_list basic.target "${basic_target_wants[@]:+${basic_target_wants[@]}}"
 
-    local script="\
-#!/bin/sh
-
-mkdir -p /run/tliset
-exec > /run/tliset/log 2>&1
-
-date '+%Y-%m-%d_%H:%M:%S'
-
-set -x -u
-
-mkdir -p ${gen_mkdir_list[*]}
-"
-    if [[ ${#gen_body[@]} -ne 0 ]]; then
-	local gen_body_txt
-	printf -v gen_body_txt '%s\n' "${gen_body[@]}"
-	script+="$gen_body_txt"
-    fi
-
-    local dir="/etc/systemd/system-generators"
-    if under_qubes; then
-	ensure_dir "/usr/local"
-	dir="/usr/local/etc"
-    fi
-
-    ensure_dir "${dir}"
-    write_file -m 0755 "${dir}/tliset" "$script"
-    if test -n "${file_update}"; then
-	if under_qubes; then
-	    "${dir}/tliset"
-	fi
+    if test -n "${systemd_unit_update}"; then
 	cmd_log systemctl daemon-reload
     fi
-}
-
-p_add_raw() {
-    gen_body+=("$1")
-}
-
-p_nl() {
-    p_add_raw ''
 }
 
 # The first argument is <kind>:<subpath> where kind specifies
@@ -557,27 +546,40 @@ p_file() {
     file_kind_and_path="$1"
     body="$2"
     local path
-    convert_shell_kind_path "${file_kind_and_path}"
+    convert_kind_path "${file_kind_and_path}"
     path="${R}"
     note_path "${path}"
-    local escaped_path
-    escape_for_shell "${path}"
-    escaped_path="${R}"
-    escape_for_shell "${body}"
-    p_add_raw "> ${escaped_path} printf %s ${R}"
+
+    set --
     if test -n "${executable}"; then
-	p_add_raw "chmod 755 ${escaped_path}"
+	set -- "$@" -m 0755
+    fi
+    write_file "$@" "${path}" "${body}"
+    if test -n "${file_update}"; then
+	case "${file_kind_and_path}" in
+	service:* ) systemd_unit_update=1 ;;
+	esac
     fi
 }
 
 p_dir() {
     local dir
     dir="$1"
-    convert_shell_kind_path "${dir}"
+    convert_kind_path "${dir}"
     dir="${R}"
     note_path "${dir}"
-    escape_for_shell "${dir}"
-    gen_mkdir_list+=("$R")
+
+    ensure_dir "${dir}"
+}
+
+p_symlink() {
+    local target path
+    target="$1"
+    path="$2"
+    convert_kind_path "${path}"
+    path="${R}"
+    note_path "${path}"
+    ensure_symlink "${target}" "${path}"
 }
 
 p_systemd_drop_in() {
@@ -585,64 +587,57 @@ p_systemd_drop_in() {
     unit_name="$1"
     drop_in_text="$2"
 
-    p_nl
     p_dir "service:${unit_name}.d"
     p_file "service:${unit_name}.d/tliset.conf" "${drop_in_text}"
 }
 
-p_cmd() {
-    local s="" arg
-    for arg in "$@"; do
-	if [[ $arg == *:* ]]; then
-	    convert_shell_kind_path "$arg"
-	    arg="${R}"
-	fi
-	escape_for_shell "$arg"
-	s+="${s:+ }$R"
-    done
-    p_add_raw "$s"
-}
-
-convert_shell_kind_path() {
-    local file_kind_and_path="$1"
-    local file_kind="${file_kind_and_path%%:*}"
-    [[ $file_kind != $file_kind_and_path ]] || err "the argument must start with <kind>: prefix"
-    local file_path="${file_kind_and_path#*:}"
-    local dir absolute=0
-    case "$file_kind" in
-    service ) dir='/run/systemd/system' ;;
-    net ) dir='/run/systemd/network' ;;
-    config ) dir="$gen_config" ;;
-    mount ) dir="$gen_mount" ;;
-    scripts ) dir="$gen_scripts" ;;
-    top ) dir="" ; absolute=1 ;;
-    nspawn )
-	dir='/run/systemd/nspawn'
-	with_nspawn_configs=1
-	;;
-    * ) err "Unknown dir_kind $dir_kind" ;;
-    esac
-    if let absolute; then
-	[[ $file_path =~ ^/. ]] || err "$file_kind must come with absolute path: $file_kind_and_path"
-    else
-	if [[ $file_path == '' ]]; then
-	    R="$dir"
-	    return 0
-	fi
-	[[ $file_path =~ ^[^/] ]] || \
-	    err "$file_kind must come with relative path: $file_kind_and_path"
-	dir+="/"
+convert_kind_path() {
+    local file_kind_and_path file_kind file_path
+    file_kind_and_path="$1"
+    file_kind="${file_kind_and_path%%:*}:"
+    file_path="${file_kind_and_path#*:}"
+    if test "x${file_path}" = "x${file_kind_and_path}"; then
+	err "the argument must start with <kind>: prefix - ${file_kind_and_path}"
     fi
-    R="${dir}${file_path}"
+    local dir
+    case "$file_kind" in
+    service: ) dir='/etc/systemd/system' ;;
+    net: ) dir='/etc/systemd/network' ;;
+    scripts: ) dir="/var/lib/tliset" ;;
+    nspawn: )
+	dir='/etc/systemd/nspawn'
+	;;
+    * ) err "Unknown file kind - ${file_kind_and_path}" ;;
+    esac
+    ensure_dir "${dir}"
+    note_path "${dir}"
+
+    if test -z "${file_path}"; then
+	R="$dir"
+	return 0
+    fi
+    case "${file_path}" in
+	/* ) err "the path part must be a relative path: ${file_kind_and_path}" ;;
+    esac
+    R="${dir}/${file_path}"
 }
 
 p_mask_service() {
-    p_cmd ln -s /dev/null "service:$1"
+    p_symlink /dev/null "service:$1"
 }
 
 setup_kernel_parameters() {
     if let with_zswap; then
-	p_add_raw 'printf 1 > /sys/module/zswap/parameters/enabled || :'
+	local unit
+	unit=tliset-zswap.service
+	p_file "service:${unit}" '
+[Service]
+Type=oneshot
+ExecStart=/bin/sh -c "printf 1 > /sys/module/zswap/parameters/enabled"
+ExecStop=/bin/sh -c "printf 0 > /sys/module/zswap/parameters/enabled"
+RemainAfterExit=yes
+'
+	basic_target_wants+=("${unit}")
     fi
     setup_zram
 }
@@ -652,43 +647,41 @@ setup_zram() {
 
     log "Checking zram"
 
-    p_nl
-    p_file top:/run/tliset/zram-enable.sh '
+    p_file -x scripts:zram-enable.sh '
+#!/bin/sh
 set -e -u
 
 SWAP_SIZE='"$zram_size"'
 
 num_cpus=$(grep -c processor /proc/cpuinfo)
-if [[ 0 = "$num_cpus" ]]; then
+if test 0 -eq "${num_cpus}"; then
     num_cpus=1
 fi
 
-rm -f /run/tliset/zram-device
-device="$(zramctl --find --size "$SWAP_SIZE" -t "$num_cpus")"
-printf "%s\\n" "$device" > /run/tliset/zram-device
+rm -f /run/tliset-zram-device
+device="$(zramctl --find --size "${SWAP_SIZE}" -t "${num_cpus}")"
+printf "%s\\n" "${device}" > /run/tliset-zram-device
 
-/sbin/mkswap "$device"
-/sbin/swapon -p 100 "$device"
+/sbin/mkswap "${device}"
+/sbin/swapon -p 100 "${device}"
 '
 
-    p_nl
-    p_file top:/run/tliset/zram-disable.sh "$(cat <<'EOF'
+    p_file scripts:zram-disable.sh "$(cat <<'EOF'
 #!/bin/sh
 set -e -u
 
 device=
-[[ -f /run/tliset/zram-device ]] || exit 0
-read -r device < /run/tliset/zram-device || :
-[[ $device ]] || exit 0
-if grep -q "^$device\\s" /proc/swaps; then
-    /sbin/swapoff "$device"
+test -f /run/tliset-zram-device || exit 0
+read -r device < /run/tliset-zram-device || :
+test -n "${device}" || exit 0
+if grep -q "^${device}\\s" /proc/swaps; then
+    /sbin/swapoff "${device}"
 fi
-zramctl --reset "$device"
-rm /run/tliset/zram-device
+zramctl --reset "${device}"
+rm /run/tliset-zram-device
 EOF
 )"
 
-    p_nl
     p_file service:tliset-zram.service "\
 [Unit]
 Description=Service enabling RAM compression using zRam
@@ -699,14 +692,13 @@ WantedBy=multi-user.target
 [Service]
 Type=oneshot
 ExecStart=/sbin/modprobe zram num_devices=1
-ExecStart=/bin/bash /run/tliset/zram-enable.sh
-ExecStop=/bin/bash /run/tliset/zram-disable.sh
+ExecStart=/bin/sh /var/lib/tliset/zram-enable.sh
+ExecStop=/bin/sh /var/lib/tliset/zram-disable.sh
 RemainAfterExit=yes
 "
     multi_user_wants+=(tliset-zram.service)
 
 }
-
 
 setup_network() {
     log "Checking network"
@@ -730,7 +722,7 @@ UseDomains=true
     fi
 
     if [[ ${NAME} == thip ]]; then
-	write_file "/etc/systemd/network/40-nspawn1.network" "\
+	p_file "net:40-nspawn1.network" "\
 [Match]
 Name=*-nspawn1
 
@@ -786,7 +778,7 @@ After=network-online.target
 Wants=network-online.target
 
 [Service]
-ExecStart=/bin/bash $gen_scripts/bergenrabbit-backup.bash
+ExecStart=/bin/bash /var/lib/tliset/bergenrabbit-backup.bash
 StandardError=journal
 StandardOutput=journal
 Type=oneshot
@@ -794,7 +786,8 @@ Type=oneshot
     multi_user_wants+=("tliset-bergenrabbit-backup.timer")
 
     # Script source with condition code
-    local s='#!/usr/bin/bash
+    local s
+    s='#!/usr/bin/bash
 set -e -u -o pipefail
 
 # Number of days to keep old backups in the changed dir
@@ -802,8 +795,8 @@ max_keep_changed_days=90
 
 '
     # On fedora change SELinux context for rsync so it is treated as
-    # a binary. As an update can reset it, do it each time before running
-    # rsync.
+    # a binary, not a service. As an update can reset it, do it each
+    # time we are about to run it.
     if let kind_fedora; then
 	s+='
 se_context=$(stat -c %C /usr/bin/rsync)
@@ -913,7 +906,6 @@ setup_services() {
 	if [[ $docker_lib_dir ]]; then
 	    local unit
 	    unit="$(systemd-escape -p "/var/lib/docker").mount"
-	    p_nl
 	    p_file "service:$unit" "\
 [Mount]
 Where=/var/lib/docker
@@ -967,7 +959,6 @@ What=$docker_lib_dir
     if [[ ${NAME} == thip ]]; then
 	local unit
 	unit="$(systemd-escape -p "/vol").mount"
-	p_nl
 	p_file "service:${unit}" "\
 [Mount]
 Where=/vol
@@ -980,7 +971,6 @@ Type=ext4
 	mount_path=/run/projects
 	local unit
 	unit="$(systemd-escape -p "${mount_path}").mount"
-	p_nl
 	p_file "service:${unit}" "\
 [Mount]
 Where=${mount_path}
@@ -1305,7 +1295,7 @@ if let kind_fedora; then
     fedora_release="$(rpm -E %fedora)"
 fi
 
-setup_tliset
+begin_tliset
 
 if ! under_qubes; then
     setup_packages
@@ -1323,5 +1313,7 @@ finish_generator_write
 
 # Run services after the docker is configured
 setup_docker_services
+
+end_tliset
 
 log "Done."
