fixes for zram setup under Ubuntu

diff --git a/zram-setup b/zram-setup
--- a/zram-setup
+++ b/zram-setup
@@ -32,18 +32,35 @@ EOF
     p_file top:/run/tliset/zram-enable.sh "$(cat <<'EOF'
 set -e -u
 
-read ignore memtotal <<eof
-$(grep -o '\<MemTotal:\s\+[0-9]\+' /proc/meminfo)
-eof
-SWAP_SIZE=$(($memtotal * 2 * 1024))
+read_memtotal() {
+	memtotal=
+	{
+		local line
+		while read -r line; do
+			if [[ $line =~ ^MemTotal:[[:blank:]]*([0-9]+)[[:blank:]]+(.*)$ ]]; then
+				memtotal="${BASH_REMATCH[1]}"
+				local units="${BASH_REMATCH[2]}"
+				[[ $units == kB ]] || err "unexpected MemTotal units $units"
+				local scale=1024
+				memtotal="$((memtotal * scale))"
+			fi
+		done
+		local a=1
+	} < /proc/meminfo
+	[[ $memtotal ]] || err "Failed to locate MemTotal in /proc/meminfo"
+}
+
+read_memtotal
+SWAP_SIZE=$(($memtotal / 10 * 18))
 
 num_cpus=$(grep -c processor /proc/cpuinfo)
 if [[ 0 = "$num_cpus" ]]; then
     num_cpus=1
 fi
 
-device=/dev/zram0
-zramctl "$device" --size "$SWAP_SIZE" -t "$num_cpus"
+rm -f /run/tliset/zram-device
+device="$(zramctl --find --size "$SWAP_SIZE" -t "$num_cpus")"
+printf '%s\n' "$device" > /run/tliset/zram-device
 
 /sbin/mkswap "$device"
 /sbin/swapon -p 100 "$device"
@@ -55,10 +72,15 @@ EOF
 #!/bin/sh
 set -e -u
 
-if grep -q '^/dev/zram0\s' /proc/swaps; then
-    /sbin/swapoff /dev/zram0
-    zramctl --reset /dev/zram0
+device=
+[[ -f /run/tliset/zram-device ]] || exit 0
+read -r device < /run/tliset/zram-device || :
+[[ $device ]] || exit 0
+if grep -q "^$device\\s" /proc/swaps; then
+    /sbin/swapoff "$device"
 fi
+zramctl --reset "$device"
+rm /run/tliset/zram-device
 EOF
 )"
 
@@ -73,8 +95,8 @@ WantedBy=multi-user.target
 [Service]
 Type=oneshot
 ExecStart=/sbin/modprobe zram num_devices=1
-ExecStart=/bin/sh /run/tliset/zram-enable.sh
-ExecStop=/bin/sh /run/tliset/zram-disable.sh
+ExecStart=/bin/bash /run/tliset/zram-enable.sh
+ExecStop=/bin/bash /run/tliset/zram-disable.sh
 RemainAfterExit=yes
 "
     multi_user_wants+=(tliset-zram.service)
